SET(CMAKE_SYSTEM_NAME Windows)

# for classical mingw32
# see http://www.mingw.org/
#set(COMPILER_PREFIX "i586-mingw32msvc")
# for 32 or 64 bits mingw-w64
#set(COMPILER_PREFIX "i686-w64-mingw32")
SET(COMPILER_PREFIX "x86_64-w64-mingw32")
FIND_PROGRAM(CMAKE_RC_COMPILER NAMES ${COMPILER_PREFIX}-windres)
FIND_PROGRAM(CMAKE_C_COMPILER NAMES ${COMPILER_PREFIX}-gcc)
FIND_PROGRAM(CMAKE_CXX_COMPILER NAMES ${COMPILER_PREFIX}-g++)
SET(CMAKE_FIND_ROOT_PATH  /usr/${COMPILER_PREFIX})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
